esphome:
  name: st25r-local-test
  on_boot:
    priority: 600
    then:
      - delay: 5s
      - logger.log: "BOOT_SIGNAL"

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: VERY_VERBOSE
  hardware_uart: USB_SERIAL_JTAG

external_components:
  - source:
      type: local
      path: components
    components: [st25r, st25r_spi]

spi:
  clk_pin: GPIO19
  miso_pin: GPIO20
  mosi_pin: GPIO18

st25r_spi:
  id: my_st25r
  cs_pin: GPIO9
  update_interval: 1s
  on_tag:
    then:
      - logger.log:
          format: "Tag detected: %s"
          args: ['x.c_str()']

binary_sensor:
  - platform: st25r
    st25r_id: my_st25r
    name: "Test Tag"
    uid: "01-02-03-04"
