esphome:
  name: st25r3916b-steval

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

spi:
  clk_pin: GPIO19
  miso_pin: GPIO10
  mosi_pin: GPIO18

external_components:
  - source:
      type: local
      path: components

output:
  - platform: gpio
    pin: GPIO2
    id: status_led_out

light:
  - platform: binary
    output: status_led_out
    id: status_led
st25r_spi:
  id: my_st25r
  cs_pin: GPIO6
  irq_pin: GPIO7
  supply_3v3: false
  update_interval: 500ms
  on_tag_scan:
    then:
      - light.turn_on: status_led
  on_tag:
    then:
      - logger.log:
          format: "Tag detected! UID: %s"
          args: [ 'x.c_str()' ]
  on_tag_removed:
    then:
      - light.turn_off: status_led
      - logger.log: "Tag removed!"

binary_sensor:
  - platform: st25r
    uid: "00-00-00-00"
    name: "Placeholder Tag"

logger:
  level: VERY_VERBOSE
  hardware_uart: USB_SERIAL_JTAG
