# Advanced ESPHome configuration for ST25R NFC Reader
# Implementation of an Access Control System

esphome:
  name: st25r-access-control
  friendly_name: ST25R Access Control

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6

logger:
  level: INFO

wifi:
  ssid: "WIFI_SSID"
  password: "WIFI_PASSWORD"

external_components:
  - source: github://JohnMcLear/esphome-st25r
    components: [ st25r, st25r_spi, st25r_i2c ]

# Enable SPI bus
spi:
  clk_pin: GPIO19
  mosi_pin: GPIO10
  miso_pin: GPIO18

# ST25R NFC Reader via SPI
st25r_spi:
  id: nfc_reader
  cs_pin: GPIO7
  irq_pin: GPIO6
  update_interval: 500ms
  
  on_tag:
    - lambda: |-
        // List of authorized UIDs (Hex format without separators)
        std::vector<std::string> authorized = {
          "041AA7675F6180",
          "01020304"
        };
        
        if (std::find(authorized.begin(), authorized.end(), x) != authorized.end()) {
          ESP_LOGI("access", "Access GRANTED for Tag: %s", x.c_str());
          id(door_lock).turn_on();
        } else {
          ESP_LOGW("access", "Access DENIED for Tag: %s", x.c_str());
        }

# Control a relay or electronic lock
switch:
  - platform: gpio
    name: "Door Lock"
    id: door_lock
    pin: GPIO15
    on_turn_on:
      - delay: 5s
      - switch.turn_off: door_lock

# Status LEDs
status_led:
  pin: GPIO8
