# Example ESPHome configuration for ST25R NFC Reader
esphome:
  name: st25r-nfc-reader
  friendly_name: ST25R NFC Reader

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6

logger:
  level: DEBUG

wifi:
  ssid: "ST25R Fallback"
  password: "PASSWORD"

external_components:
  - source: github://JohnMcLear/esphome-st25r
    components: [ st25r, st25r_spi, st25r_i2c ]

# Enable SPI bus
spi:
  clk_pin: GPIO19
  mosi_pin: GPIO10
  miso_pin: GPIO18

# Configure ST25R NFC reader via SPI
st25r_spi:
  id: my_st25r
  cs_pin: GPIO7
  irq_pin: GPIO6
  update_interval: 1s
  
  # Tag detection triggers
  on_tag:
    - lambda: |-
        ESP_LOGI("main", "Tag detected: %s", x.c_str());
        
  on_tag_removed:
    - lambda: |-
        ESP_LOGI("main", "Tag removed: %s", x.c_str());

# Optional: Create a binary sensor for a specific tag
binary_sensor:
  - platform: st25r
    st25r_id: my_st25r
    name: "Master Key"
    uid: "04-1A-A7-67-5F-61-80"
